python pipelines/train.py \
--config-name=config.yaml \
job_id="md17-salicylic_acid" \
data_name=rmd-salicylic_acid \
dataset_path="/data/qhflow-mlff/dataset/md-salicylic_acid" \
devices=[0,7] \
wandb.wandb_api_key=$WANDB_API_KEY \
lr=0.0005 \
enable_hami=True \
hami_weight=1  \
batch_size=32 \
schedule=polynomial \
schedule.lr_warmup_steps=1000 \
max_steps=100000 \
train_ratio=0.8 \
val_ratio=0.1 \
test_ratio=0.1 \
gradient_clip_val=5.0 \
dataset_size=-1